; Translated from PeTTa to HE (7 atoms)
; Source: examples/matespace.metta
; Translation target: PeTTa HE
; Intended runtime: ./run.sh --he
; Portability: portable/default HE lowering

(= (length $expr) (let $tuple (eval $expr) (size-atom $tuple)))
(= (add-atom-no-duplicate $Space $Atom) (if (== () (collapse (once (match $Space $Atom $Atom)))) (add-atom $Space $Atom) (empty)))
(= (expand) (case (match &self (num $t) $t) (($t ((add-atom-no-duplicate &self (num (M $t))) (add-atom-no-duplicate &self (num (W $t))))))))
(= (mate) (case (match &self (num (M $t)) $t) (($t (case (once (match &self (num (W $t)) $t)) (($t (add-atom-no-duplicate &self (num (C $t))))))))))
(= (expandK $n) (if (== $n 0) done (let $temp1 (expand) (expandK (- $n 1)))))
(= (mate-space-demo $K) (let* (($s (add-atom &self (num Z))) ($g (expandK $K)) ($h (mate))) (match &self (num $1) (num $1))))
!(test (let $__tr_tuple_1 (collapse (mate-space-demo 390)) (size-atom $__tr_tuple_1)) 1063919)
